### ISSUE TITLE
Play Music March update breaks styling

### ISSUE THREAD

**Issue by macfeaster** [chrisxclash/play-midnight#20] opened 2016-04-05 18:09 UTC
Fantastic work on this theme!
In late March, Google rolled out some minor updates to Play Music which broke styling a little:

* The Google Play Music logo in the sidebar has a white background
* The black background on list views stretches all the way to the window edge (supposed to show a strip of the big hero image on each side of e.g. a playlist)

**Comment by chrisxclash** [comment] 2016-04-05 18:12
@macfeaster Thanks sir!

Can you provide me a few screenshots of what you're talking about real quick? (Specifically your second bullet). I can't seem to see any of the changes yet on my end, but Google's been slow to roll out changes that I've seen sometimes.

Thanks!

**Comment by macfeaster** [comment] 2016-04-05 18:24
@chrisxclash Of course! They are both visible in this screenshot.
As you can see, there is a black area on both sides of the album view where the big image should shine through (which it did before Google rolled out changes.)

![Play Music](http://i.imgur.com/PYI7Sxn.png)

**Comment by chrisxclash** [comment] 2016-04-05 18:45
@macfeaster Awesome, thanks!

I figured out the issue with the black hero image background, but I can't reproduce the white logo at the moment. I don't think it will be too big of an issue to fix though.

Thanks for letting me know!

**Comment by macfeaster** [comment] 2016-04-05 19:00
@chrisxclash No problem, thank you for looking into it!

The logo is made white by the following CSS rule:
```
#nav-container .nav-toolbar {
    background-color: white;
}
```

**Comment by macfeaster** [comment] 2016-08-04 19:12
Hi! Wanted to check in and see if any progress was made on this? If fixed, would it be possible to update the [userstyle](https://userstyles.org/styles/115630/play-midnight-for-google-play-music) too?

**Comment by chrisxclash** [comment] 2016-08-08 15:15
Hey, sorry I've actually been on quite the hiatus recently so I haven't really done much work on Play Midnight. Probably partially because I switched to Tidal for a while, but I'm coming back to Play Midnight when I can. I can't make any promises on when I'll be able to do the main work I've been wanting to (just moved, some changes at work) but I still would like to get to it when I have time.

In the meantime, if you want to take a stab at it, I'm always happy to accept a pull request for fixes.

Best,
Chris

**Comment by geudrik** [comment] 2016-09-13 15:30
This issue should be closed and marked as resolved

**Comment by chrisxclash** [comment] 2016-09-13 16:33
Closing this for now, I'll create another ticket to update the userstyles at some point.

**Closed by chrisxclash** 2016-09-13 16:33 UTC
Labels: styling

**Comment by macfeaster** [comment] 2016-09-13 18:38
Nice to see progress has been made! Looking forward to an update of the userstyle, which lags behind since Oct 2015.
