### ISSUE TITLE
CSS Accent color not changing between states

### ISSUE THREAD

**Issue by KTruong008** [chrisxclash/play-midnight#43] opened 2017-12-16 20:15 UTC
**Expected behaviour:**

When I click the loop or shuffle buttons (the loopy arrows or the criss cross arrows), the colour should change to my accented colour to indicate a change in state.

**Actual behaviour:**

When I click the loop or shuffle buttons (the loopy arrows or the criss cross arrows), the colour remains white (inactive colour) instead of the accented colour chosen (orange in my case).

**Other Information**

I noticed this happening sometime early this week or late last week. I tried tinkering with some live-css and plopping some !important tags in but that didn't work either

<img width="879" alt="2017-12-16-play-midnight-css-bug" src="https://user-images.githubusercontent.com/17548405/34073982-e13ba882-e273-11e7-8aa0-35c67cbabc00.png">

**Comment by chrisxclash** [comment] 2017-12-18 16:42
Thanks for letting me know. I've heard from one other person about it, and it shouldn't hopefully be too big of an issue to fix up. It's most likely due to an update to Google's paper/iron buttons and the way the active state is added now.

I've tinkered a little bit but haven't had a chance to dig in completely yet. I'll try and get it fixed up this week. Thanks for letting me know!

**Comment by nathaned** [comment] 2018-01-20 22:35
Has this issue been fixed (on Google's side)? I can't seem to reproduce the issue.

**Comment by chrisxclash** [comment] 2018-01-29 09:06
Should be fixed in v3.0.0 👍

**Closed by chrisxclash** 2018-01-29 09:06 UTC
